apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: issuedb
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_PW
              value: Init1234
            - name: POSTGRES_USER
              value: issueuser
            - name: RESTAPI_HOST
              value: restapi
            - name: RESTAPI_PORT
              value: "5000"
          image: frontend
          name: frontend
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
