"""uaers, issues table

Revision ID: 18f2d75b3734
Revises: 
Create Date: 2021-07-27 23:50:34.994261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f2d75b3734'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=220), nullable=True),
    sa.Column('user_id', sa.String(length=60), nullable=True),
    sa.Column('issue_action', sa.String(length=60), nullable=True),
    sa.Column('issue_title', sa.String(length=120), nullable=True),
    sa.Column('issue_state', sa.String(length=60), nullable=True),
    sa.Column('issue_html_url', sa.String(length=220), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('user_html_url', sa.String(length=220), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_modified_date'), 'issue', ['modified_date'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_issue_modified_date'), table_name='issue')
    op.drop_table('issue')
    # ### end Alembic commands ###
