"""issues table

Revision ID: bfe4cc0f7370
Revises: 9598bff39a66
Create Date: 2021-07-25 18:45:36.816646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe4cc0f7370'
down_revision = '9598bff39a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=220), nullable=True),
    sa.Column('user_id', sa.String(length=60), nullable=True),
    sa.Column('issue_action', sa.String(length=60), nullable=True),
    sa.Column('issue_title', sa.String(length=120), nullable=True),
    sa.Column('issue_state', sa.String(length=60), nullable=True),
    sa.Column('issue_html_url', sa.String(length=220), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('user_html_url', sa.String(length=220), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar_url'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_issue_modified_date'), 'issue', ['modified_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_modified_date'), table_name='issue')
    op.drop_table('issue')
    # ### end Alembic commands ###
